FROM python:3.11-slim

RUN apt-get update -y && apt-get upgrade -y && apt-get install git -y

WORKDIR /documentation

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENTRYPOINT [ "python", "-m", "mkdocs" ]
CMD ["--help"]