# Dockerfile for MkDocs with uv on Alpine Linux
FROM ghcr.io/astral-sh/uv:python3.13-alpine

# Add git
RUN apk --no-cache add git

# Set working directory
WORKDIR /documentation

# Install requirements
COPY requirements.txt ./
RUN uv pip install --system --no-cache -r requirements.txt

# Copy files
COPY . .

# Expose port
EXPOSE 8000

# Run application
ENTRYPOINT [ "python", "-m", "mkdocs" ]
CMD ["--help"]